# Imagen base
FROM python:3.11-slim

# Crear dir de trabajo
RUN mkdir /app
COPY . /app/
WORKDIR /app

# Exponer el puerto donde recibe
EXPOSE 5000

# Ejecuta el Receptor
CMD ["python", "Receptor.py"]
