#  Imagen base
FROM python:3.11-slim

# Crear dir de trabajo
RUN mkdir /app
COPY . /app/
WORKDIR /app

# ⚡️ Instalar cualquier dependencia (opcional, por si acaso)
RUN pip install --no-cache-dir tqdm

#  Ejecuta el Emisor
CMD ["python", "Emisor.py"]
