services:
  receptor:
    build:
      context: ..
      dockerfile: dockerfile.receptor
    container_name: receptor
    environment:
      - PYTHONUNBUFFERED=1
      #- ERROR=True
      #- E_PERCENT=0.1
    volumes:
      - ./metrics:/app/metrics
    ports:
      - "5000:5000/udp"
    networks:
      - mi_red_interna



  emisor:
    build:
      context: ..
      dockerfile: dockerfile.emisor
    container_name: emisor
    depends_on:
      - receptor
    command: ["sh", "-c", "sleep 5 && python Emisor.py"]
    environment:
      - RECEIVER_HOST=receptor
      - RECEIVER_PORT=5000
      - PYTHONUNBUFFERED=1
      - ERROR=True
      - E_ERROR=0.1
    volumes:
      - ./metrics:/app/metrics
    networks:
      - mi_red_interna
  chaos:
    image: gaiaadm/pumba:latest
    container_name: chaos
    command: ["netem", "--duration", "60m", 
              "delay", "-t", "5000", "-j", "500", "-c", "20",
              "loss","-p" ,"50","-c","30",
              "corrupt","-p","20","-c","10",
              "duplicate", "-p", "25",  "emisor"]
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - receptor
    networks:
      - mi_red_interna

  chaos_delay:
    image: gaiaadm/pumba:latest
    container_name: chaos_delay
    command: ["netem", "--duration", "60m", 
              "delay", "-t", "5000", "-j", "500", "-c", "20",
              "emisor"]
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - receptor
    networks:
      - mi_red_interna

  chaos_loss:
    image: gaiaadm/pumba:latest
    container_name: chaos_loss
    command: ["netem", "--duration", "60m", "loss","--percent" ,"50","--correlation","30", "emisor"]
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - receptor
    networks:
      - mi_red_interna

  chaos_corruption:
    image: gaiaadm/pumba:latest
    container_name: chaos_corruption
    command: ["netem", "--duration", "60m", "corrupt","--percent","90","--correlation","50", "emisor"]
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - receptor
    networks:
      - mi_red_interna
      
  chaos_duplicate:
    image: gaiaadm/pumba:latest
    container_name: chaos_duplicate
    command: ["--log-level", "debug","netem", "--duration", "60m", "duplicate", "-p", "25","-c","20", "emisor"]
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - receptor
    networks:
      - mi_red_interna


networks:
  mi_red_interna:
    driver: bridge